/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AAddOneAddExp extends PAddExp
{
    private PMulExp _mulExp_;

    public AAddOneAddExp()
    {
        // Constructor
    }

    public AAddOneAddExp(
        @SuppressWarnings("hiding") PMulExp _mulExp_)
    {
        // Constructor
        setMulExp(_mulExp_);

    }

    @Override
    public Object clone()
    {
        return new AAddOneAddExp(
            cloneNode(this._mulExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddOneAddExp(this);
    }

    public PMulExp getMulExp()
    {
        return this._mulExp_;
    }

    public void setMulExp(PMulExp node)
    {
        if(this._mulExp_ != null)
        {
            this._mulExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mulExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._mulExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._mulExp_ == child)
        {
            this._mulExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._mulExp_ == oldChild)
        {
            setMulExp((PMulExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
