/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AAndTermAndExp extends PAndExp
{
    private PRelExp _relExp_;

    public AAndTermAndExp()
    {
        // Constructor
    }

    public AAndTermAndExp(
        @SuppressWarnings("hiding") PRelExp _relExp_)
    {
        // Constructor
        setRelExp(_relExp_);

    }

    @Override
    public Object clone()
    {
        return new AAndTermAndExp(
            cloneNode(this._relExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndTermAndExp(this);
    }

    public PRelExp getRelExp()
    {
        return this._relExp_;
    }

    public void setRelExp(PRelExp node)
    {
        if(this._relExp_ != null)
        {
            this._relExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relExp_ == child)
        {
            this._relExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relExp_ == oldChild)
        {
            setRelExp((PRelExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
