/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AAndExpRMoreAndExpRparen extends PAndExpRparen
{
    private PRelExp _relExp_;
    private TAnd _and_;
    private PAndExpRparen _andExpRparen_;

    public AAndExpRMoreAndExpRparen()
    {
        // Constructor
    }

    public AAndExpRMoreAndExpRparen(
        @SuppressWarnings("hiding") PRelExp _relExp_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PAndExpRparen _andExpRparen_)
    {
        // Constructor
        setRelExp(_relExp_);

        setAnd(_and_);

        setAndExpRparen(_andExpRparen_);

    }

    @Override
    public Object clone()
    {
        return new AAndExpRMoreAndExpRparen(
            cloneNode(this._relExp_),
            cloneNode(this._and_),
            cloneNode(this._andExpRparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndExpRMoreAndExpRparen(this);
    }

    public PRelExp getRelExp()
    {
        return this._relExp_;
    }

    public void setRelExp(PRelExp node)
    {
        if(this._relExp_ != null)
        {
            this._relExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relExp_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PAndExpRparen getAndExpRparen()
    {
        return this._andExpRparen_;
    }

    public void setAndExpRparen(PAndExpRparen node)
    {
        if(this._andExpRparen_ != null)
        {
            this._andExpRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExpRparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relExp_)
            + toString(this._and_)
            + toString(this._andExpRparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relExp_ == child)
        {
            this._relExp_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._andExpRparen_ == child)
        {
            this._andExpRparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relExp_ == oldChild)
        {
            setRelExp((PRelExp) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._andExpRparen_ == oldChild)
        {
            setAndExpRparen((PAndExpRparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
