/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class ABoolValor extends PValor
{
    private TValorBooleano _valorBooleano_;

    public ABoolValor()
    {
        // Constructor
    }

    public ABoolValor(
        @SuppressWarnings("hiding") TValorBooleano _valorBooleano_)
    {
        // Constructor
        setValorBooleano(_valorBooleano_);

    }

    @Override
    public Object clone()
    {
        return new ABoolValor(
            cloneNode(this._valorBooleano_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolValor(this);
    }

    public TValorBooleano getValorBooleano()
    {
        return this._valorBooleano_;
    }

    public void setValorBooleano(TValorBooleano node)
    {
        if(this._valorBooleano_ != null)
        {
            this._valorBooleano_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorBooleano_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valorBooleano_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valorBooleano_ == child)
        {
            this._valorBooleano_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valorBooleano_ == oldChild)
        {
            setValorBooleano((TValorBooleano) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
