/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class ACmdsOptComCmdsOpt extends PCmdsOpt
{
    private PListaComando _listaComando_;

    public ACmdsOptComCmdsOpt()
    {
        // Constructor
    }

    public ACmdsOptComCmdsOpt(
        @SuppressWarnings("hiding") PListaComando _listaComando_)
    {
        // Constructor
        setListaComando(_listaComando_);

    }

    @Override
    public Object clone()
    {
        return new ACmdsOptComCmdsOpt(
            cloneNode(this._listaComando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACmdsOptComCmdsOpt(this);
    }

    public PListaComando getListaComando()
    {
        return this._listaComando_;
    }

    public void setListaComando(PListaComando node)
    {
        if(this._listaComando_ != null)
        {
            this._listaComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComando_ == child)
        {
            this._listaComando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComando_ == oldChild)
        {
            setListaComando((PListaComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
