/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AComandoSCondComando extends PComando
{
    private PComandoSemCond _comandoSemCond_;

    public AComandoSCondComando()
    {
        // Constructor
    }

    public AComandoSCondComando(
        @SuppressWarnings("hiding") PComandoSemCond _comandoSemCond_)
    {
        // Constructor
        setComandoSemCond(_comandoSemCond_);

    }

    @Override
    public Object clone()
    {
        return new AComandoSCondComando(
            cloneNode(this._comandoSemCond_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoSCondComando(this);
    }

    public PComandoSemCond getComandoSemCond()
    {
        return this._comandoSemCond_;
    }

    public void setComandoSemCond(PComandoSemCond node)
    {
        if(this._comandoSemCond_ != null)
        {
            this._comandoSemCond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSemCond_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoSemCond_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoSemCond_ == child)
        {
            this._comandoSemCond_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoSemCond_ == oldChild)
        {
            setComandoSemCond((PComandoSemCond) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
