/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AComandoForComandoSemCond extends PComandoSemCond
{
    private PForStmt _forStmt_;

    public AComandoForComandoSemCond()
    {
        // Constructor
    }

    public AComandoForComandoSemCond(
        @SuppressWarnings("hiding") PForStmt _forStmt_)
    {
        // Constructor
        setForStmt(_forStmt_);

    }

    @Override
    public Object clone()
    {
        return new AComandoForComandoSemCond(
            cloneNode(this._forStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoForComandoSemCond(this);
    }

    public PForStmt getForStmt()
    {
        return this._forStmt_;
    }

    public void setForStmt(PForStmt node)
    {
        if(this._forStmt_ != null)
        {
            this._forStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._forStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._forStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._forStmt_ == child)
        {
            this._forStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._forStmt_ == oldChild)
        {
            setForStmt((PForStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
