/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AComandoWhileComandoSemCond extends PComandoSemCond
{
    private PWhileStmt _whileStmt_;

    public AComandoWhileComandoSemCond()
    {
        // Constructor
    }

    public AComandoWhileComandoSemCond(
        @SuppressWarnings("hiding") PWhileStmt _whileStmt_)
    {
        // Constructor
        setWhileStmt(_whileStmt_);

    }

    @Override
    public Object clone()
    {
        return new AComandoWhileComandoSemCond(
            cloneNode(this._whileStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoWhileComandoSemCond(this);
    }

    public PWhileStmt getWhileStmt()
    {
        return this._whileStmt_;
    }

    public void setWhileStmt(PWhileStmt node)
    {
        if(this._whileStmt_ != null)
        {
            this._whileStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileStmt_ == child)
        {
            this._whileStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileStmt_ == oldChild)
        {
            setWhileStmt((PWhileStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
