/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AElseTailElseTail extends PElseTail
{
    private TOtherwise _otherwise_;
    private TDo _do_;
    private PComando _comando_;

    public AElseTailElseTail()
    {
        // Constructor
    }

    public AElseTailElseTail(
        @SuppressWarnings("hiding") TOtherwise _otherwise_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setOtherwise(_otherwise_);

        setDo(_do_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AElseTailElseTail(
            cloneNode(this._otherwise_),
            cloneNode(this._do_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseTailElseTail(this);
    }

    public TOtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(TOtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otherwise_)
            + toString(this._do_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otherwise_ == oldChild)
        {
            setOtherwise((TOtherwise) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
