/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyAddTail extends PAddTail
{

    public AEmptyAddTail()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyAddTail();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyAddTail(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
