/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AListaHeadListaComando extends PListaComando
{
    private PListaComandoTail _listaComandoTail_;
    private PComando _comando_;

    public AListaHeadListaComando()
    {
        // Constructor
    }

    public AListaHeadListaComando(
        @SuppressWarnings("hiding") PListaComandoTail _listaComandoTail_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setListaComandoTail(_listaComandoTail_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AListaHeadListaComando(
            cloneNode(this._listaComandoTail_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaHeadListaComando(this);
    }

    public PListaComandoTail getListaComandoTail()
    {
        return this._listaComandoTail_;
    }

    public void setListaComandoTail(PListaComandoTail node)
    {
        if(this._listaComandoTail_ != null)
        {
            this._listaComandoTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandoTail_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComandoTail_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComandoTail_ == child)
        {
            this._listaComandoTail_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComandoTail_ == oldChild)
        {
            setListaComandoTail((PListaComandoTail) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
