/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AListaVariosComandos extends PListaVariosComandos
{
    private PListaComandoRec _listaComandoRec_;
    private PComando _comando_;

    public AListaVariosComandos()
    {
        // Constructor
    }

    public AListaVariosComandos(
        @SuppressWarnings("hiding") PListaComandoRec _listaComandoRec_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setListaComandoRec(_listaComandoRec_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AListaVariosComandos(
            cloneNode(this._listaComandoRec_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaVariosComandos(this);
    }

    public PListaComandoRec getListaComandoRec()
    {
        return this._listaComandoRec_;
    }

    public void setListaComandoRec(PListaComandoRec node)
    {
        if(this._listaComandoRec_ != null)
        {
            this._listaComandoRec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComandoRec_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComandoRec_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComandoRec_ == child)
        {
            this._listaComandoRec_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComandoRec_ == oldChild)
        {
            setListaComandoRec((PListaComandoRec) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
