/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AListaComandoRec extends PListaComandoRec
{
    private PListaVariosComandos _listaVariosComandos_;

    public AListaComandoRec()
    {
        // Constructor
    }

    public AListaComandoRec(
        @SuppressWarnings("hiding") PListaVariosComandos _listaVariosComandos_)
    {
        // Constructor
        setListaVariosComandos(_listaVariosComandos_);

    }

    @Override
    public Object clone()
    {
        return new AListaComandoRec(
            cloneNode(this._listaVariosComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComandoRec(this);
    }

    public PListaVariosComandos getListaVariosComandos()
    {
        return this._listaVariosComandos_;
    }

    public void setListaVariosComandos(PListaVariosComandos node)
    {
        if(this._listaVariosComandos_ != null)
        {
            this._listaVariosComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaVariosComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaVariosComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaVariosComandos_ == child)
        {
            this._listaVariosComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaVariosComandos_ == oldChild)
        {
            setListaVariosComandos((PListaVariosComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
