/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AListaDeclaracaoRecListaDeclaracao extends PListaDeclaracao
{
    private PListaDeclaracao _listaDeclaracao_;
    private PDeclaracao _declaracao_;

    public AListaDeclaracaoRecListaDeclaracao()
    {
        // Constructor
    }

    public AListaDeclaracaoRecListaDeclaracao(
        @SuppressWarnings("hiding") PListaDeclaracao _listaDeclaracao_,
        @SuppressWarnings("hiding") PDeclaracao _declaracao_)
    {
        // Constructor
        setListaDeclaracao(_listaDeclaracao_);

        setDeclaracao(_declaracao_);

    }

    @Override
    public Object clone()
    {
        return new AListaDeclaracaoRecListaDeclaracao(
            cloneNode(this._listaDeclaracao_),
            cloneNode(this._declaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaDeclaracaoRecListaDeclaracao(this);
    }

    public PListaDeclaracao getListaDeclaracao()
    {
        return this._listaDeclaracao_;
    }

    public void setListaDeclaracao(PListaDeclaracao node)
    {
        if(this._listaDeclaracao_ != null)
        {
            this._listaDeclaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDeclaracao_ = node;
    }

    public PDeclaracao getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(PDeclaracao node)
    {
        if(this._declaracao_ != null)
        {
            this._declaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaDeclaracao_)
            + toString(this._declaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaDeclaracao_ == child)
        {
            this._listaDeclaracao_ = null;
            return;
        }

        if(this._declaracao_ == child)
        {
            this._declaracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaDeclaracao_ == oldChild)
        {
            setListaDeclaracao((PListaDeclaracao) newChild);
            return;
        }

        if(this._declaracao_ == oldChild)
        {
            setDeclaracao((PDeclaracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
