/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AListaArgMoreListaArgRparen extends PListaArgRparen
{
    private PExp _exp_;
    private TVirgula _virgula_;
    private PListaArgRparen _listaArgRparen_;

    public AListaArgMoreListaArgRparen()
    {
        // Constructor
    }

    public AListaArgMoreListaArgRparen(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PListaArgRparen _listaArgRparen_)
    {
        // Constructor
        setExp(_exp_);

        setVirgula(_virgula_);

        setListaArgRparen(_listaArgRparen_);

    }

    @Override
    public Object clone()
    {
        return new AListaArgMoreListaArgRparen(
            cloneNode(this._exp_),
            cloneNode(this._virgula_),
            cloneNode(this._listaArgRparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaArgMoreListaArgRparen(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PListaArgRparen getListaArgRparen()
    {
        return this._listaArgRparen_;
    }

    public void setListaArgRparen(PListaArgRparen node)
    {
        if(this._listaArgRparen_ != null)
        {
            this._listaArgRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaArgRparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._virgula_)
            + toString(this._listaArgRparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._listaArgRparen_ == child)
        {
            this._listaArgRparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._listaArgRparen_ == oldChild)
        {
            setListaArgRparen((PListaArgRparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
