/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AListaComandoTail extends PListaComandoTail
{
    private PListaFim _listaFim_;

    public AListaComandoTail()
    {
        // Constructor
    }

    public AListaComandoTail(
        @SuppressWarnings("hiding") PListaFim _listaFim_)
    {
        // Constructor
        setListaFim(_listaFim_);

    }

    @Override
    public Object clone()
    {
        return new AListaComandoTail(
            cloneNode(this._listaFim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComandoTail(this);
    }

    public PListaFim getListaFim()
    {
        return this._listaFim_;
    }

    public void setListaFim(PListaFim node)
    {
        if(this._listaFim_ != null)
        {
            this._listaFim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaFim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaFim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaFim_ == child)
        {
            this._listaFim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaFim_ == oldChild)
        {
            setListaFim((PListaFim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
