/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AMatchedTail extends PMatchedTail
{
    private TOtherwise _otherwise_;
    private PListaComando _listaComando_;

    public AMatchedTail()
    {
        // Constructor
    }

    public AMatchedTail(
        @SuppressWarnings("hiding") TOtherwise _otherwise_,
        @SuppressWarnings("hiding") PListaComando _listaComando_)
    {
        // Constructor
        setOtherwise(_otherwise_);

        setListaComando(_listaComando_);

    }

    @Override
    public Object clone()
    {
        return new AMatchedTail(
            cloneNode(this._otherwise_),
            cloneNode(this._listaComando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatchedTail(this);
    }

    public TOtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(TOtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    public PListaComando getListaComando()
    {
        return this._listaComando_;
    }

    public void setListaComando(PListaComando node)
    {
        if(this._listaComando_ != null)
        {
            this._listaComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otherwise_)
            + toString(this._listaComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        if(this._listaComando_ == child)
        {
            this._listaComando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otherwise_ == oldChild)
        {
            setOtherwise((TOtherwise) newChild);
            return;
        }

        if(this._listaComando_ == oldChild)
        {
            setListaComando((PListaComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
