/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AMulDivMulExp extends PMulExp
{
    private PUnaryExp _unaryExp_;
    private TDiv _div_;
    private PMulExp _mulExp_;

    public AMulDivMulExp()
    {
        // Constructor
    }

    public AMulDivMulExp(
        @SuppressWarnings("hiding") PUnaryExp _unaryExp_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PMulExp _mulExp_)
    {
        // Constructor
        setUnaryExp(_unaryExp_);

        setDiv(_div_);

        setMulExp(_mulExp_);

    }

    @Override
    public Object clone()
    {
        return new AMulDivMulExp(
            cloneNode(this._unaryExp_),
            cloneNode(this._div_),
            cloneNode(this._mulExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMulDivMulExp(this);
    }

    public PUnaryExp getUnaryExp()
    {
        return this._unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node)
    {
        if(this._unaryExp_ != null)
        {
            this._unaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExp_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PMulExp getMulExp()
    {
        return this._mulExp_;
    }

    public void setMulExp(PMulExp node)
    {
        if(this._mulExp_ != null)
        {
            this._mulExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mulExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unaryExp_)
            + toString(this._div_)
            + toString(this._mulExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unaryExp_ == child)
        {
            this._unaryExp_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._mulExp_ == child)
        {
            this._mulExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unaryExp_ == oldChild)
        {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._mulExp_ == oldChild)
        {
            setMulExp((PMulExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
