/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AOrNormOrExp extends POrExp
{
    private PAndExp _andExp_;
    private POrTail _orTail_;

    public AOrNormOrExp()
    {
        // Constructor
    }

    public AOrNormOrExp(
        @SuppressWarnings("hiding") PAndExp _andExp_,
        @SuppressWarnings("hiding") POrTail _orTail_)
    {
        // Constructor
        setAndExp(_andExp_);

        setOrTail(_orTail_);

    }

    @Override
    public Object clone()
    {
        return new AOrNormOrExp(
            cloneNode(this._andExp_),
            cloneNode(this._orTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrNormOrExp(this);
    }

    public PAndExp getAndExp()
    {
        return this._andExp_;
    }

    public void setAndExp(PAndExp node)
    {
        if(this._andExp_ != null)
        {
            this._andExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExp_ = node;
    }

    public POrTail getOrTail()
    {
        return this._orTail_;
    }

    public void setOrTail(POrTail node)
    {
        if(this._orTail_ != null)
        {
            this._orTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orTail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andExp_)
            + toString(this._orTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andExp_ == child)
        {
            this._andExp_ = null;
            return;
        }

        if(this._orTail_ == child)
        {
            this._orTail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andExp_ == oldChild)
        {
            setAndExp((PAndExp) newChild);
            return;
        }

        if(this._orTail_ == oldChild)
        {
            setOrTail((POrTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
