/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AOrOneOrExp extends POrExp
{
    private PAndExp _andExp_;

    public AOrOneOrExp()
    {
        // Constructor
    }

    public AOrOneOrExp(
        @SuppressWarnings("hiding") PAndExp _andExp_)
    {
        // Constructor
        setAndExp(_andExp_);

    }

    @Override
    public Object clone()
    {
        return new AOrOneOrExp(
            cloneNode(this._andExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrOneOrExp(this);
    }

    public PAndExp getAndExp()
    {
        return this._andExp_;
    }

    public void setAndExp(PAndExp node)
    {
        if(this._andExp_ != null)
        {
            this._andExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._andExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._andExp_ == child)
        {
            this._andExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._andExp_ == oldChild)
        {
            setAndExp((PAndExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
