/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class ARelLtRelTail extends PRelTail
{
    private TMenor _menor_;
    private PAddExp _addExp_;

    public ARelLtRelTail()
    {
        // Constructor
    }

    public ARelLtRelTail(
        @SuppressWarnings("hiding") TMenor _menor_,
        @SuppressWarnings("hiding") PAddExp _addExp_)
    {
        // Constructor
        setMenor(_menor_);

        setAddExp(_addExp_);

    }

    @Override
    public Object clone()
    {
        return new ARelLtRelTail(
            cloneNode(this._menor_),
            cloneNode(this._addExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelLtRelTail(this);
    }

    public TMenor getMenor()
    {
        return this._menor_;
    }

    public void setMenor(TMenor node)
    {
        if(this._menor_ != null)
        {
            this._menor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menor_ = node;
    }

    public PAddExp getAddExp()
    {
        return this._addExp_;
    }

    public void setAddExp(PAddExp node)
    {
        if(this._addExp_ != null)
        {
            this._addExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menor_)
            + toString(this._addExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menor_ == child)
        {
            this._menor_ = null;
            return;
        }

        if(this._addExp_ == child)
        {
            this._addExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menor_ == oldChild)
        {
            setMenor((TMenor) newChild);
            return;
        }

        if(this._addExp_ == oldChild)
        {
            setAddExp((PAddExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
