/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AUnNegUnaryExp extends PUnaryExp
{
    private TMenos _menos_;
    private PUnaryExp _unaryExp_;

    public AUnNegUnaryExp()
    {
        // Constructor
    }

    public AUnNegUnaryExp(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PUnaryExp _unaryExp_)
    {
        // Constructor
        setMenos(_menos_);

        setUnaryExp(_unaryExp_);

    }

    @Override
    public Object clone()
    {
        return new AUnNegUnaryExp(
            cloneNode(this._menos_),
            cloneNode(this._unaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnNegUnaryExp(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PUnaryExp getUnaryExp()
    {
        return this._unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node)
    {
        if(this._unaryExp_ != null)
        {
            this._unaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._unaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._unaryExp_ == child)
        {
            this._unaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._unaryExp_ == oldChild)
        {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
