/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class AVarCallVar extends PVar
{
    private TIdentificador _identificador_;
    private TParEsq _parEsq_;
    private PListaArgRparen _listaArgRparen_;

    public AVarCallVar()
    {
        // Constructor
    }

    public AVarCallVar(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PListaArgRparen _listaArgRparen_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setParEsq(_parEsq_);

        setListaArgRparen(_listaArgRparen_);

    }

    @Override
    public Object clone()
    {
        return new AVarCallVar(
            cloneNode(this._identificador_),
            cloneNode(this._parEsq_),
            cloneNode(this._listaArgRparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarCallVar(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PListaArgRparen getListaArgRparen()
    {
        return this._listaArgRparen_;
    }

    public void setListaArgRparen(PListaArgRparen node)
    {
        if(this._listaArgRparen_ != null)
        {
            this._listaArgRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaArgRparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._parEsq_)
            + toString(this._listaArgRparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._listaArgRparen_ == child)
        {
            this._listaArgRparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._listaArgRparen_ == oldChild)
        {
            setListaArgRparen((PListaArgRparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
