/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class TAbandon extends Token
{
    public TAbandon()
    {
        super.setText("abandon");
    }

    public TAbandon(int line, int pos)
    {
        super.setText("abandon");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAbandon(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAbandon(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAbandon text.");
    }
}
