/* This file was generated by SableCC (http://www.sablecc.org/). */

package grupo_18.node;

import grupo_18.analysis.*;

@SuppressWarnings("nls")
public final class TLet extends Token
{
    public TLet()
    {
        super.setText("Let");
    }

    public TLet(int line, int pos)
    {
        super.setText("Let");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLet(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLet(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLet text.");
    }
}
