/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ACmdSoltComando extends PComando
{
    private PComandoSolteiro _comandoSolteiro_;

    public ACmdSoltComando()
    {
        // Constructor
    }

    public ACmdSoltComando(
        @SuppressWarnings("hiding") PComandoSolteiro _comandoSolteiro_)
    {
        // Constructor
        setComandoSolteiro(_comandoSolteiro_);

    }

    @Override
    public Object clone()
    {
        return new ACmdSoltComando(
            cloneNode(this._comandoSolteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACmdSoltComando(this);
    }

    public PComandoSolteiro getComandoSolteiro()
    {
        return this._comandoSolteiro_;
    }

    public void setComandoSolteiro(PComandoSolteiro node)
    {
        if(this._comandoSolteiro_ != null)
        {
            this._comandoSolteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSolteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoSolteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoSolteiro_ == child)
        {
            this._comandoSolteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoSolteiro_ == oldChild)
        {
            setComandoSolteiro((PComandoSolteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
