/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AComandoCondComando extends PComando
{
    private PJustStmt _justStmt_;

    public AComandoCondComando()
    {
        // Constructor
    }

    public AComandoCondComando(
        @SuppressWarnings("hiding") PJustStmt _justStmt_)
    {
        // Constructor
        setJustStmt(_justStmt_);

    }

    @Override
    public Object clone()
    {
        return new AComandoCondComando(
            cloneNode(this._justStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoCondComando(this);
    }

    public PJustStmt getJustStmt()
    {
        return this._justStmt_;
    }

    public void setJustStmt(PJustStmt node)
    {
        if(this._justStmt_ != null)
        {
            this._justStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._justStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._justStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._justStmt_ == child)
        {
            this._justStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._justStmt_ == oldChild)
        {
            setJustStmt((PJustStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
