/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AIfCasaComandoCasado extends PComandoCasado
{
    private TJust _just_;
    private TIn _in_;
    private TCase _case_;
    private TThatKw _thatKw_;
    private TParEsq _parEsq_;
    private PExp _exp_;
    private TParDir _parDir_;
    private TDo _a_;
    private PComandoCasado _bidi_;
    private TOtherwise _otherwise_;
    private TDo _c_;
    private PComandoCasado _dibi_;

    public AIfCasaComandoCasado()
    {
        // Constructor
    }

    public AIfCasaComandoCasado(
        @SuppressWarnings("hiding") TJust _just_,
        @SuppressWarnings("hiding") TIn _in_,
        @SuppressWarnings("hiding") TCase _case_,
        @SuppressWarnings("hiding") TThatKw _thatKw_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") TDo _a_,
        @SuppressWarnings("hiding") PComandoCasado _bidi_,
        @SuppressWarnings("hiding") TOtherwise _otherwise_,
        @SuppressWarnings("hiding") TDo _c_,
        @SuppressWarnings("hiding") PComandoCasado _dibi_)
    {
        // Constructor
        setJust(_just_);

        setIn(_in_);

        setCase(_case_);

        setThatKw(_thatKw_);

        setParEsq(_parEsq_);

        setExp(_exp_);

        setParDir(_parDir_);

        setA(_a_);

        setBidi(_bidi_);

        setOtherwise(_otherwise_);

        setC(_c_);

        setDibi(_dibi_);

    }

    @Override
    public Object clone()
    {
        return new AIfCasaComandoCasado(
            cloneNode(this._just_),
            cloneNode(this._in_),
            cloneNode(this._case_),
            cloneNode(this._thatKw_),
            cloneNode(this._parEsq_),
            cloneNode(this._exp_),
            cloneNode(this._parDir_),
            cloneNode(this._a_),
            cloneNode(this._bidi_),
            cloneNode(this._otherwise_),
            cloneNode(this._c_),
            cloneNode(this._dibi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfCasaComandoCasado(this);
    }

    public TJust getJust()
    {
        return this._just_;
    }

    public void setJust(TJust node)
    {
        if(this._just_ != null)
        {
            this._just_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._just_ = node;
    }

    public TIn getIn()
    {
        return this._in_;
    }

    public void setIn(TIn node)
    {
        if(this._in_ != null)
        {
            this._in_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._in_ = node;
    }

    public TCase getCase()
    {
        return this._case_;
    }

    public void setCase(TCase node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    public TThatKw getThatKw()
    {
        return this._thatKw_;
    }

    public void setThatKw(TThatKw node)
    {
        if(this._thatKw_ != null)
        {
            this._thatKw_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._thatKw_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public TDo getA()
    {
        return this._a_;
    }

    public void setA(TDo node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public PComandoCasado getBidi()
    {
        return this._bidi_;
    }

    public void setBidi(PComandoCasado node)
    {
        if(this._bidi_ != null)
        {
            this._bidi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bidi_ = node;
    }

    public TOtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(TOtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    public TDo getC()
    {
        return this._c_;
    }

    public void setC(TDo node)
    {
        if(this._c_ != null)
        {
            this._c_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._c_ = node;
    }

    public PComandoCasado getDibi()
    {
        return this._dibi_;
    }

    public void setDibi(PComandoCasado node)
    {
        if(this._dibi_ != null)
        {
            this._dibi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dibi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._just_)
            + toString(this._in_)
            + toString(this._case_)
            + toString(this._thatKw_)
            + toString(this._parEsq_)
            + toString(this._exp_)
            + toString(this._parDir_)
            + toString(this._a_)
            + toString(this._bidi_)
            + toString(this._otherwise_)
            + toString(this._c_)
            + toString(this._dibi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._just_ == child)
        {
            this._just_ = null;
            return;
        }

        if(this._in_ == child)
        {
            this._in_ = null;
            return;
        }

        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        if(this._thatKw_ == child)
        {
            this._thatKw_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._bidi_ == child)
        {
            this._bidi_ = null;
            return;
        }

        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        if(this._c_ == child)
        {
            this._c_ = null;
            return;
        }

        if(this._dibi_ == child)
        {
            this._dibi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._just_ == oldChild)
        {
            setJust((TJust) newChild);
            return;
        }

        if(this._in_ == oldChild)
        {
            setIn((TIn) newChild);
            return;
        }

        if(this._case_ == oldChild)
        {
            setCase((TCase) newChild);
            return;
        }

        if(this._thatKw_ == oldChild)
        {
            setThatKw((TThatKw) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((TDo) newChild);
            return;
        }

        if(this._bidi_ == oldChild)
        {
            setBidi((PComandoCasado) newChild);
            return;
        }

        if(this._otherwise_ == oldChild)
        {
            setOtherwise((TOtherwise) newChild);
            return;
        }

        if(this._c_ == oldChild)
        {
            setC((TDo) newChild);
            return;
        }

        if(this._dibi_ == oldChild)
        {
            setDibi((PComandoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
