/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AIfElseIfTailBlk extends PIfTailBlk
{
    private TOtherwise _otherwise_;
    private TDo _do_;
    private PBloco _elseBlk_;

    public AIfElseIfTailBlk()
    {
        // Constructor
    }

    public AIfElseIfTailBlk(
        @SuppressWarnings("hiding") TOtherwise _otherwise_,
        @SuppressWarnings("hiding") TDo _do_,
        @SuppressWarnings("hiding") PBloco _elseBlk_)
    {
        // Constructor
        setOtherwise(_otherwise_);

        setDo(_do_);

        setElseBlk(_elseBlk_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseIfTailBlk(
            cloneNode(this._otherwise_),
            cloneNode(this._do_),
            cloneNode(this._elseBlk_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseIfTailBlk(this);
    }

    public TOtherwise getOtherwise()
    {
        return this._otherwise_;
    }

    public void setOtherwise(TOtherwise node)
    {
        if(this._otherwise_ != null)
        {
            this._otherwise_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._otherwise_ = node;
    }

    public TDo getDo()
    {
        return this._do_;
    }

    public void setDo(TDo node)
    {
        if(this._do_ != null)
        {
            this._do_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._do_ = node;
    }

    public PBloco getElseBlk()
    {
        return this._elseBlk_;
    }

    public void setElseBlk(PBloco node)
    {
        if(this._elseBlk_ != null)
        {
            this._elseBlk_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseBlk_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._otherwise_)
            + toString(this._do_)
            + toString(this._elseBlk_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._otherwise_ == child)
        {
            this._otherwise_ = null;
            return;
        }

        if(this._do_ == child)
        {
            this._do_ = null;
            return;
        }

        if(this._elseBlk_ == child)
        {
            this._elseBlk_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._otherwise_ == oldChild)
        {
            setOtherwise((TOtherwise) newChild);
            return;
        }

        if(this._do_ == oldChild)
        {
            setDo((TDo) newChild);
            return;
        }

        if(this._elseBlk_ == oldChild)
        {
            setElseBlk((PBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
