/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AIfThenElseComando extends PComando
{
    private PExp _exp_;
    private PComando _a_;
    private PComando _b_;

    public AIfThenElseComando()
    {
        // Constructor
    }

    public AIfThenElseComando(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PComando _a_,
        @SuppressWarnings("hiding") PComando _b_)
    {
        // Constructor
        setExp(_exp_);

        setA(_a_);

        setB(_b_);

    }

    @Override
    public Object clone()
    {
        return new AIfThenElseComando(
            cloneNode(this._exp_),
            cloneNode(this._a_),
            cloneNode(this._b_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfThenElseComando(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PComando getA()
    {
        return this._a_;
    }

    public void setA(PComando node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public PComando getB()
    {
        return this._b_;
    }

    public void setB(PComando node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._a_)
            + toString(this._b_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._a_ == oldChild)
        {
            setA((PComando) newChild);
            return;
        }

        if(this._b_ == oldChild)
        {
            setB((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
