/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ALargHeadListaArgRparen extends PListaArgRparen
{
    private POrExpRparen _orExpRparen_;

    public ALargHeadListaArgRparen()
    {
        // Constructor
    }

    public ALargHeadListaArgRparen(
        @SuppressWarnings("hiding") POrExpRparen _orExpRparen_)
    {
        // Constructor
        setOrExpRparen(_orExpRparen_);

    }

    @Override
    public Object clone()
    {
        return new ALargHeadListaArgRparen(
            cloneNode(this._orExpRparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALargHeadListaArgRparen(this);
    }

    public POrExpRparen getOrExpRparen()
    {
        return this._orExpRparen_;
    }

    public void setOrExpRparen(POrExpRparen node)
    {
        if(this._orExpRparen_ != null)
        {
            this._orExpRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orExpRparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._orExpRparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._orExpRparen_ == child)
        {
            this._orExpRparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._orExpRparen_ == oldChild)
        {
            setOrExpRparen((POrExpRparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
