/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class AOrRComOrTailRparen extends POrTailRparen
{
    private TVirgula _virgula_;
    private PListaExpRparen _listaExpRparen_;

    public AOrRComOrTailRparen()
    {
        // Constructor
    }

    public AOrRComOrTailRparen(
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PListaExpRparen _listaExpRparen_)
    {
        // Constructor
        setVirgula(_virgula_);

        setListaExpRparen(_listaExpRparen_);

    }

    @Override
    public Object clone()
    {
        return new AOrRComOrTailRparen(
            cloneNode(this._virgula_),
            cloneNode(this._listaExpRparen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrRComOrTailRparen(this);
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PListaExpRparen getListaExpRparen()
    {
        return this._listaExpRparen_;
    }

    public void setListaExpRparen(PListaExpRparen node)
    {
        if(this._listaExpRparen_ != null)
        {
            this._listaExpRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExpRparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgula_)
            + toString(this._listaExpRparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._listaExpRparen_ == child)
        {
            this._listaExpRparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._listaExpRparen_ == oldChild)
        {
            setListaExpRparen((PListaExpRparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
