/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ARelEqRelTail extends PRelTail
{
    private TIgual _igual_;
    private PAddExp _addExp_;

    public ARelEqRelTail()
    {
        // Constructor
    }

    public ARelEqRelTail(
        @SuppressWarnings("hiding") TIgual _igual_,
        @SuppressWarnings("hiding") PAddExp _addExp_)
    {
        // Constructor
        setIgual(_igual_);

        setAddExp(_addExp_);

    }

    @Override
    public Object clone()
    {
        return new ARelEqRelTail(
            cloneNode(this._igual_),
            cloneNode(this._addExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelEqRelTail(this);
    }

    public TIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(TIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    public PAddExp getAddExp()
    {
        return this._addExp_;
    }

    public void setAddExp(PAddExp node)
    {
        if(this._addExp_ != null)
        {
            this._addExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._igual_)
            + toString(this._addExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        if(this._addExp_ == child)
        {
            this._addExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._igual_ == oldChild)
        {
            setIgual((TIgual) newChild);
            return;
        }

        if(this._addExp_ == oldChild)
        {
            setAddExp((PAddExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
