/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ARelGeRelTail extends PRelTail
{
    private TMaiorigual _maiorigual_;
    private PAddExp _addExp_;

    public ARelGeRelTail()
    {
        // Constructor
    }

    public ARelGeRelTail(
        @SuppressWarnings("hiding") TMaiorigual _maiorigual_,
        @SuppressWarnings("hiding") PAddExp _addExp_)
    {
        // Constructor
        setMaiorigual(_maiorigual_);

        setAddExp(_addExp_);

    }

    @Override
    public Object clone()
    {
        return new ARelGeRelTail(
            cloneNode(this._maiorigual_),
            cloneNode(this._addExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelGeRelTail(this);
    }

    public TMaiorigual getMaiorigual()
    {
        return this._maiorigual_;
    }

    public void setMaiorigual(TMaiorigual node)
    {
        if(this._maiorigual_ != null)
        {
            this._maiorigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorigual_ = node;
    }

    public PAddExp getAddExp()
    {
        return this._addExp_;
    }

    public void setAddExp(PAddExp node)
    {
        if(this._addExp_ != null)
        {
            this._addExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorigual_)
            + toString(this._addExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorigual_ == child)
        {
            this._maiorigual_ = null;
            return;
        }

        if(this._addExp_ == child)
        {
            this._addExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorigual_ == oldChild)
        {
            setMaiorigual((TMaiorigual) newChild);
            return;
        }

        if(this._addExp_ == oldChild)
        {
            setAddExp((PAddExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
