/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ASymbolTipo extends PTipo
{

    public ASymbolTipo()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ASymbolTipo();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASymbolTipo(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
