/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class ATamanhosMatrizTamanhos extends PTamanhos
{
    private PTamanhos _tamanhos_;
    private TVezes _vezes_;
    private TInteiro _inteiro_;

    public ATamanhosMatrizTamanhos()
    {
        // Constructor
    }

    public ATamanhosMatrizTamanhos(
        @SuppressWarnings("hiding") PTamanhos _tamanhos_,
        @SuppressWarnings("hiding") TVezes _vezes_,
        @SuppressWarnings("hiding") TInteiro _inteiro_)
    {
        // Constructor
        setTamanhos(_tamanhos_);

        setVezes(_vezes_);

        setInteiro(_inteiro_);

    }

    @Override
    public Object clone()
    {
        return new ATamanhosMatrizTamanhos(
            cloneNode(this._tamanhos_),
            cloneNode(this._vezes_),
            cloneNode(this._inteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATamanhosMatrizTamanhos(this);
    }

    public PTamanhos getTamanhos()
    {
        return this._tamanhos_;
    }

    public void setTamanhos(PTamanhos node)
    {
        if(this._tamanhos_ != null)
        {
            this._tamanhos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tamanhos_ = node;
    }

    public TVezes getVezes()
    {
        return this._vezes_;
    }

    public void setVezes(TVezes node)
    {
        if(this._vezes_ != null)
        {
            this._vezes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vezes_ = node;
    }

    public TInteiro getInteiro()
    {
        return this._inteiro_;
    }

    public void setInteiro(TInteiro node)
    {
        if(this._inteiro_ != null)
        {
            this._inteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tamanhos_)
            + toString(this._vezes_)
            + toString(this._inteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tamanhos_ == child)
        {
            this._tamanhos_ = null;
            return;
        }

        if(this._vezes_ == child)
        {
            this._vezes_ = null;
            return;
        }

        if(this._inteiro_ == child)
        {
            this._inteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tamanhos_ == oldChild)
        {
            setTamanhos((PTamanhos) newChild);
            return;
        }

        if(this._vezes_ == oldChild)
        {
            setVezes((TVezes) newChild);
            return;
        }

        if(this._inteiro_ == oldChild)
        {
            setInteiro((TInteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
