/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TVezes extends Token
{
    public TVezes()
    {
        super.setText("x");
    }

    public TVezes(int line, int pos)
    {
        super.setText("x");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVezes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVezes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVezes text.");
    }
}
